### ISSUE TITLE
Sample for IIS hosted SCIM endpoint using ASP.NET Core and VS 2017

### ISSUE THREAD

**Issue by thuru** [Azure/AzureAD-BYOA-Provisioning-Samples#11]
Hi, 
Is there any sample for IIS hosted SCIM service with ASP.NET Core using VS 2017 ? Also is it possible to host such endpoint in a Azure Web Apps.

**Comment by craigmcm** [comment]
Thanks for your question.  No, there is no sample for hosting in ASP.NET Core.  As for hosting options generally, the Service library provides an ASP.NET OWIN service, and any container that can host ASP.NET OWIN can be used.

Craig McMurtry
Developer, Identity Platform

Microsoft Corporation
Building 28, Office 2082
1 Microsoft Way, Redmond, WA, 98052

Office: +1.425.707.9810|Mobile: +1.425.503.2854|Fax: +1.425.936.7329
